branches:
  only:
  - master
  - develop
language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - ARDUINO_IDE_VERSION="1.8.10"
    - PRETTYNAME="Arduino library for the I²C Multiplexer TCA9548A"
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/teamonestone/travis-ci-arduino/master/install.sh)
install:
script:
  - build_main_platforms
after_success:
  - source <(curl -SLs https://raw.githubusercontent.com/teamonestone/travis-ci-arduino/master/doxy_gen_and_deploy.sh)